kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: jenkins-pv
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jenkins"
